name: oycrm
description: Oyster Telecom mobile CRM

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  flutter_svg: ^0.18.1
  get_it: ^4.0.0
  flutter_conditional_rendering: ^1.0.0
  rxdart: ^0.24.0
  shared_preferences: ^0.5.0
  provider: ^4.0.0
  flutter_icons: ^1.1.0
  firebase_messaging: ^6.0.16
  cached_network_image: ^2.2.0
  expandable: ^4.1.4
  photo_view: ^0.10.2
  socket_io_client: ^0.9.10
  laravel_echo: ^0.2.2
  url_launcher: ^5.5.0
  image_picker: ^0.6.7+4
  file_picker: ^1.13.3
  flutter_html: ^1.0.0-pre.1
  html: ^0.14.0+3
  flutter_datetime_picker: ^1.3.8
  bubble_tab_indicator: ^0.1.4
  pull_to_refresh: ^1.6.0
  flutter_launcher_icons: ^0.7.5
  sentry: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/images/ic_launcher_ios.png"
  image_path_android: "lib/assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
     - lib/assets/images/logo.svg
     - lib/assets/images/logo.png
     - lib/assets/images/ic_launcher.png
     - lib/assets/images/trello.svg

  fonts:
     - family: OpenSans
       fonts:
         - asset: lib/assets/fonts/OpenSans-Regular.ttf
     - family: OpenSansExtraBold
       fonts:
         - asset: lib/assets/fonts/OpenSans-ExtraBold.ttf
     - family: TTcommonsBold
       fonts:
         - asset: lib/assets/fonts/tt_commons_bold.otf
